import { MigrationInterface, QueryRunner } from "typeorm";

export class PivotSchemaInit1767765458300 implements MigrationInterface {
    name = 'PivotSchemaInit1767765458300'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_99d90c2a483d79f3b627fb1d5e9"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_9e9662808426cca2f97d6526c58"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_cdb99c05982d5191ac8465ac010"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_ff6014136574d2e1c1df0a6bf33"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "UQ_27f93dc477434cffcd926c2da0b"`);
        await queryRunner.query(`CREATE TABLE "merchants" ("id" SERIAL NOT NULL, "name" character varying(120) NOT NULL, "phone" character varying(20) NOT NULL, "whatsapp_number" character varying(20) NOT NULL, "category" character varying(50), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4fd312ef25f8e05ad47bfe7ed25" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stores" ("id" SERIAL NOT NULL, "merchant_id" integer NOT NULL, "name" character varying(120) NOT NULL, "slug" character varying(120) NOT NULL, "is_open" boolean NOT NULL DEFAULT true, "address_text" text, "latitude" numeric(10,7), "longitude" numeric(10,7), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_790b2968701a6ff5ff383237765" UNIQUE ("slug"), CONSTRAINT "PK_7aa6e7d71fa7acdd7ca43d7c9cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" SERIAL NOT NULL, "product_id" integer NOT NULL, "label" character varying(100) NOT NULL, "unit" character varying(50), "unit_value" numeric(10,3), "price" numeric(10,2) NOT NULL, "is_default" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_events_type_enum" AS ENUM('sold', 'restocked', 'adjustment')`);
        await queryRunner.query(`CREATE TABLE "inventory_events" ("id" SERIAL NOT NULL, "product_id" integer NOT NULL, "product_variant_id" integer NOT NULL, "type" "public"."inventory_events_type_enum" NOT NULL, "quantity" numeric(10,2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2e23c05381d151be5dad80bbe10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" SERIAL NOT NULL, "name" character varying(120), "whatsapp_number" character varying(20) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7bfee32716cdb80a065fb83389" ON "customers" ("whatsapp_number") `);
        await queryRunner.query(`CREATE TABLE "order_links" ("id" SERIAL NOT NULL, "order_id" integer NOT NULL, "token" character varying(64) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cb634e668602cba41f03b0809c7" UNIQUE ("token"), CONSTRAINT "REL_e04b2c56fdf5a98bb3c1f05274" UNIQUE ("order_id"), CONSTRAINT "PK_8604cd69ddc711b1aa03237884c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "stock"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "sku"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "main_image"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "productsId"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "order_type"`);
        await queryRunner.query(`DROP TYPE "public"."orders_order_type_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "storefrontId"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "store_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD "barcode" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "products" ADD "image_url" character varying(512)`);
        await queryRunner.query(`ALTER TABLE "products" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "product_id" integer`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "product_variant_id" integer`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "variant_label" character varying(100)`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "store_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "customer_id" integer`);
        await queryRunner.query(`CREATE TYPE "public"."orders_order_source_enum" AS ENUM('whatsapp', 'web')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "order_source" "public"."orders_order_source_enum" NOT NULL DEFAULT 'web'`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_59268dba986ee39a54affbdc00e"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "id" SERIAL NOT NULL `);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "productId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "PK_005269d8574e6fac0493715c308"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "id" SERIAL NOT NULL `);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "quantity"`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "quantity" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "orderId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" DROP CONSTRAINT "FK_5d28cd60ee855c630b01ae398d0"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "id" SERIAL NOT NULL `);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TYPE "public"."orders_status_enum" RENAME TO "orders_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending', 'confirmed', 'shipped', 'cancelled', 'completed')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" TYPE "public"."orders_status_enum" USING "status"::"text"::"public"."orders_status_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" ADD "orderId" integer`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "UQ_f2ff0d6409027115aea231bc229" UNIQUE ("store_id", "barcode")`);
        await queryRunner.query(`ALTER TABLE "stores" ADD CONSTRAINT "FK_882687fd3a8a29fa5bf13858a5b" FOREIGN KEY ("merchant_id") REFERENCES "merchants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_6343513e20e2deab45edfce1316" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_events" ADD CONSTRAINT "FK_f7ddfa78eb2478787f7cc5c3552" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_events" ADD CONSTRAINT "FK_fc45514a25429fcd5d8664f9b4e" FOREIGN KEY ("product_variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_59268dba986ee39a54affbdc00e" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_11836543386b9135a47d54cab70" FOREIGN KEY ("product_variant_id") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_b7a7bb813431fc7cd73cced0001" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_links" ADD CONSTRAINT "FK_e04b2c56fdf5a98bb3c1f052749" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" ADD CONSTRAINT "FK_5d28cd60ee855c630b01ae398d0" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "custom_order_requests" DROP CONSTRAINT "FK_5d28cd60ee855c630b01ae398d0"`);
        await queryRunner.query(`ALTER TABLE "order_links" DROP CONSTRAINT "FK_e04b2c56fdf5a98bb3c1f052749"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_b7a7bb813431fc7cd73cced0001"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_11836543386b9135a47d54cab70"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_59268dba986ee39a54affbdc00e"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_68863607048a1abd43772b314ef"`);
        await queryRunner.query(`ALTER TABLE "inventory_events" DROP CONSTRAINT "FK_fc45514a25429fcd5d8664f9b4e"`);
        await queryRunner.query(`ALTER TABLE "inventory_events" DROP CONSTRAINT "FK_f7ddfa78eb2478787f7cc5c3552"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_6343513e20e2deab45edfce1316"`);
        await queryRunner.query(`ALTER TABLE "stores" DROP CONSTRAINT "FK_882687fd3a8a29fa5bf13858a5b"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "UQ_f2ff0d6409027115aea231bc229"`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" ADD "orderId" integer`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum_old" AS ENUM('pending', 'confirmed', 'shipped', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" TYPE "public"."orders_status_enum_old" USING "status"::"text"::"public"."orders_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."orders_status_enum_old" RENAME TO "orders_status_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" ADD CONSTRAINT "FK_5d28cd60ee855c630b01ae398d0" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "orderId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "quantity"`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "quantity" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "PK_005269d8574e6fac0493715c308"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "productId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_59268dba986ee39a54affbdc00e" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "order_source"`);
        await queryRunner.query(`DROP TYPE "public"."orders_order_source_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "store_id"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "variant_label"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "product_variant_id"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP COLUMN "product_id"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "image_url"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "barcode"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "store_id"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "storefrontId" integer NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."orders_order_type_enum" AS ENUM('catalog', 'custom')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "order_type" "public"."orders_order_type_enum" NOT NULL DEFAULT 'catalog'`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD "productId" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "productsId" integer`);
        await queryRunner.query(`ALTER TABLE "products" ADD "main_image" character varying(512)`);
        await queryRunner.query(`ALTER TABLE "products" ADD "sku" character varying(64)`);
        await queryRunner.query(`ALTER TABLE "products" ADD "userId" integer`);
        await queryRunner.query(`CREATE TYPE "public"."products_status_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`ALTER TABLE "products" ADD "status" "public"."products_status_enum" NOT NULL DEFAULT 'active'`);
        await queryRunner.query(`ALTER TABLE "products" ADD "stock" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD "price" integer NOT NULL`);
        await queryRunner.query(`DROP TABLE "order_links"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7bfee32716cdb80a065fb83389"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "inventory_events"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_events_type_enum"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP TABLE "stores"`);
        await queryRunner.query(`DROP TABLE "merchants"`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "UQ_27f93dc477434cffcd926c2da0b" UNIQUE ("slug", "userId")`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_ff6014136574d2e1c1df0a6bf33" FOREIGN KEY ("storefrontId") REFERENCES "storefronts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_cdb99c05982d5191ac8465ac010" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_9e9662808426cca2f97d6526c58" FOREIGN KEY ("productsId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_99d90c2a483d79f3b627fb1d5e9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
