import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateUsers1767914353960 implements MigrationInterface {
    name = 'UpdateUsers1767914353960'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "stores" DROP CONSTRAINT "FK_882687fd3a8a29fa5bf13858a5b"`);
        await queryRunner.query(`ALTER TABLE "store_themes" DROP CONSTRAINT "FK_store_themes_store_id"`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" DROP CONSTRAINT "FK_b20689c5876d8196f1e08af6a94"`);
        await queryRunner.query(`ALTER TABLE "usage_tracking" DROP CONSTRAINT "FK_5d8df20d681cd50fcde4db2db32"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_stores_location"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_users_phone"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_7bfee32716cdb80a065fb83389"`);
        await queryRunner.query(`DROP INDEX IF EXISTS "public"."IDX_store_themes_store_id"`);
        await queryRunner.query(`ALTER TABLE "stores" RENAME COLUMN "merchant_id" TO "owner_user_id"`);
        await queryRunner.query(`ALTER TABLE "usage_tracking" RENAME COLUMN "userId" TO "user_id"`);
        await queryRunner.query(`CREATE TABLE "admins" ("user_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2b901dd818a2a6486994d915a68" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" SERIAL NOT NULL, "key" character varying NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_017943867ed5ceef9c03edd9745" UNIQUE ("key"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."roles_scope_enum" AS ENUM('global', 'store')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "display_name" character varying, "scope" "public"."roles_scope_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" integer NOT NULL, "role_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE TABLE "store_user_roles" ("user_id" integer NOT NULL, "store_id" integer NOT NULL, "role_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5a1e5260c9485b7c8a75e2424ec" PRIMARY KEY ("user_id", "store_id", "role_id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" integer NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "reset_password_token"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "PK_133ec679a801fab5e070f73d3ea"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "whatsapp_number"`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" DROP COLUMN "storefrontId"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP CONSTRAINT "PK_4fd312ef25f8e05ad47bfe7ed25"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP COLUMN "whatsapp_number"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP COLUMN "category"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password_hash" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone_verified_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "user_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "PK_11d81cd7be87b6f8865b0cf7661" PRIMARY KEY ("user_id")`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "UQ_customers_id" UNIQUE ("id")`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "PK_11d81cd7be87b6f8865b0cf7661"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "PK_cbb50ac77af86114525e1282d13" PRIMARY KEY ("user_id", "id")`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "name" character varying(120)`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "whatsapp_number" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" ADD "store_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" ADD "customer_id" integer`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD "user_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD CONSTRAINT "PK_698f612a3134c503f711479a4e5" PRIMARY KEY ("user_id")`);
        await queryRunner.query(`CREATE TYPE "public"."merchants_onboarding_status_enum" AS ENUM('signup', 'business_type_selected', 'whatsapp_connected', 'store_created', 'products_added', 'live')`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD "onboarding_status" "public"."merchants_onboarding_status_enum" NOT NULL DEFAULT 'signup'`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD "primary_store_id" integer`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "store_themes" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "store_themes" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "store_themes" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "store_themes" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "IDX_f94c72515c300083297fac24fc" ON "stores" USING GiST ("location") `);
        // Add phone column before creating index (needed for fresh DB)
        await queryRunner.query(`ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "phone" character varying`);
        await queryRunner.query(`UPDATE "users" SET "phone" = 'UNKNOWN_' || "id" WHERE "phone" IS NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "phone" SET NOT NULL`);
        // Add unique constraint only if it doesn't exist (PostgreSQL doesn't support IF NOT EXISTS for constraints)
        await queryRunner.query(`
            DO $$ BEGIN
                ALTER TABLE "users" ADD CONSTRAINT "UQ_users_phone" UNIQUE ("phone");
            EXCEPTION
                WHEN duplicate_object THEN NULL;
            END $$;
        `);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_a000cca60bcf04454e72769949" ON "users" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_7bfee32716cdb80a065fb83389" ON "customers" ("whatsapp_number") `);
        await queryRunner.query(`ALTER TABLE "stores" ADD CONSTRAINT "FK_ba95f3c2644552c72431cfb0c78" FOREIGN KEY ("owner_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_11d81cd7be87b6f8865b0cf7661" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admins" ADD CONSTRAINT "FK_2b901dd818a2a6486994d915a68" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_themes" ADD CONSTRAINT "FK_106d2c55078dfad89cd368b3949" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" ADD CONSTRAINT "FK_896c63b51a136d131fc049326bc" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" ADD CONSTRAINT "FK_435af75bd28ed784b3c02bbed54" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD CONSTRAINT "FK_698f612a3134c503f711479a4e5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD CONSTRAINT "FK_e04bed4eb6d5d47a851067e58a2" FOREIGN KEY ("primary_store_id") REFERENCES "stores"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usage_tracking" ADD CONSTRAINT "FK_97e15b4afbc1ebaad4f12080878" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_user_roles" ADD CONSTRAINT "FK_ac6fbd8586dd6fff743a9c93c1c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_user_roles" ADD CONSTRAINT "FK_aecccdfb2d7191d9505431b482d" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_user_roles" ADD CONSTRAINT "FK_a97091dcc6b28eab2b3813b55f0" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "store_user_roles" DROP CONSTRAINT "FK_a97091dcc6b28eab2b3813b55f0"`);
        await queryRunner.query(`ALTER TABLE "store_user_roles" DROP CONSTRAINT "FK_aecccdfb2d7191d9505431b482d"`);
        await queryRunner.query(`ALTER TABLE "store_user_roles" DROP CONSTRAINT "FK_ac6fbd8586dd6fff743a9c93c1c"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "usage_tracking" DROP CONSTRAINT "FK_97e15b4afbc1ebaad4f12080878"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP CONSTRAINT "FK_e04bed4eb6d5d47a851067e58a2"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP CONSTRAINT "FK_698f612a3134c503f711479a4e5"`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" DROP CONSTRAINT "FK_435af75bd28ed784b3c02bbed54"`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" DROP CONSTRAINT "FK_896c63b51a136d131fc049326bc"`);
        await queryRunner.query(`ALTER TABLE "store_themes" DROP CONSTRAINT "FK_106d2c55078dfad89cd368b3949"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP CONSTRAINT "FK_2b901dd818a2a6486994d915a68"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_11d81cd7be87b6f8865b0cf7661"`);
        await queryRunner.query(`ALTER TABLE "stores" DROP CONSTRAINT "FK_ba95f3c2644552c72431cfb0c78"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7bfee32716cdb80a065fb83389"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a000cca60bcf04454e72769949"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f94c72515c300083297fac24fc"`);
        await queryRunner.query(`ALTER TABLE "store_themes" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "store_themes" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "store_themes" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "store_themes" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP COLUMN "primary_store_id"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP COLUMN "onboarding_status"`);
        await queryRunner.query(`DROP TYPE "public"."merchants_onboarding_status_enum"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP CONSTRAINT "PK_698f612a3134c503f711479a4e5"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" DROP COLUMN "customer_id"`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" DROP COLUMN "store_id"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "whatsapp_number"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "PK_cbb50ac77af86114525e1282d13"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "PK_11d81cd7be87b6f8865b0cf7661" PRIMARY KEY ("user_id")`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "PK_11d81cd7be87b6f8865b0cf7661"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone_verified_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "password_hash"`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD "category" character varying(50)`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD "whatsapp_number" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD "phone" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD "name" character varying(120) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD "is_active" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD CONSTRAINT "PK_4fd312ef25f8e05ad47bfe7ed25" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" ADD "storefrontId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "whatsapp_number" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "name" character varying(120)`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "UQ_customers_id"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "password" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "reset_password_token" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "last_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "first_name" character varying NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'user')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" "public"."users_role_enum" NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "is_active" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "store_user_roles"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_scope_enum"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "admins"`);
        await queryRunner.query(`ALTER TABLE "usage_tracking" RENAME COLUMN "user_id" TO "userId"`);
        await queryRunner.query(`ALTER TABLE "stores" RENAME COLUMN "owner_user_id" TO "merchant_id"`);
        await queryRunner.query(`CREATE INDEX "IDX_store_themes_store_id" ON "store_themes" ("store_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7bfee32716cdb80a065fb83389" ON "customers" ("whatsapp_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_users_phone" ON "users" ("phone") `);
        await queryRunner.query(`CREATE INDEX "IDX_stores_location" ON "stores" USING GiST ("location") `);
        await queryRunner.query(`ALTER TABLE "usage_tracking" ADD CONSTRAINT "FK_5d8df20d681cd50fcde4db2db32" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" ADD CONSTRAINT "FK_b20689c5876d8196f1e08af6a94" FOREIGN KEY ("storefrontId") REFERENCES "storefronts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_themes" ADD CONSTRAINT "FK_store_themes_store_id" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stores" ADD CONSTRAINT "FK_882687fd3a8a29fa5bf13858a5b" FOREIGN KEY ("merchant_id") REFERENCES "merchants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
