import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1768663576759 implements MigrationInterface {
    name = 'InitSchema1768663576759'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."user_identities_provider_enum" AS ENUM('facebook')`);
        await queryRunner.query(`CREATE TABLE "user_identities" ("id" SERIAL NOT NULL, "provider" "public"."user_identities_provider_enum" NOT NULL, "providerId" character varying NOT NULL, "accessToken" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "UQ_a810154198446b51fdf3f227c5f" UNIQUE ("provider", "providerId"), CONSTRAINT "PK_e23bff04e9c3e7b785e442b262c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "plans" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "price" integer NOT NULL, "billing_cycle" character varying NOT NULL DEFAULT 'monthly', "max_products" integer, "max_posts_per_month" integer, "max_messages_per_month" integer, "max_staff_users" integer NOT NULL DEFAULT '1', "has_custom_domain" boolean NOT NULL DEFAULT false, "has_theme_access" boolean NOT NULL DEFAULT false, "branding_removed" boolean NOT NULL DEFAULT false, "available_themes_count" integer NOT NULL DEFAULT '0', "available_color_palettes" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "display_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_253d25dae4c94ee913bc5ec4850" UNIQUE ("name"), CONSTRAINT "UQ_e7b71bb444e74ee067df057397e" UNIQUE ("slug"), CONSTRAINT "PK_3720521a81c7c24fe9b7202ba61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_subscriptions" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "planId" integer NOT NULL, "status" character varying NOT NULL DEFAULT 'active', "current_period_start" TIMESTAMP NOT NULL, "current_period_end" TIMESTAMP NOT NULL, "cancel_at_period_end" boolean NOT NULL DEFAULT false, "cancelled_at" TIMESTAMP, "payment_method" character varying, "last_payment_date" TIMESTAMP, "next_billing_date" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "REL_2dfab576863bc3f84d4f696227" UNIQUE ("userId"), CONSTRAINT "PK_9e928b0954e51705ab44988812c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" SERIAL NOT NULL, "key" character varying NOT NULL, "name_en" character varying NOT NULL, "name_ar" character varying NOT NULL, "suggested_sub_categories" jsonb NOT NULL DEFAULT '[]', "icon" character varying(50), "sort_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_da6f1e4e0c4683302df95d3ae9c" UNIQUE ("key"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."stores_type_enum" AS ENUM('physical', 'online', 'hybrid')`);
        await queryRunner.query(`CREATE TABLE "stores" ("id" SERIAL NOT NULL, "type" "public"."stores_type_enum" NOT NULL DEFAULT 'online', "owner_user_id" integer NOT NULL, "name" character varying(120) NOT NULL, "slug" character varying(120) NOT NULL, "description" text, "address_text" text, "location" geography(Point,4326), "category_id" integer, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_790b2968701a6ff5ff383237765" UNIQUE ("slug"), CONSTRAINT "PK_7aa6e7d71fa7acdd7ca43d7c9cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f94c72515c300083297fac24fc" ON "stores" USING GiST ("location") `);
        await queryRunner.query(`CREATE TYPE "public"."product_variants_unit_enum" AS ENUM('kg', 'g', 'liter', 'piece', 'pack')`);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" SERIAL NOT NULL, "product_id" integer NOT NULL, "label" character varying(100) NOT NULL, "unit" "public"."product_variants_unit_enum", "stock" integer NOT NULL, "unit_value" numeric(10,3), "price" numeric(10,2) NOT NULL, "sale_price" numeric(10,2), "cost_price" numeric(10,2), "wholesale_price" numeric(10,2), "is_default" boolean NOT NULL DEFAULT false, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_31e615e1e93111f90aa7b5ed06" ON "product_variants" ("product_id") WHERE is_default = true`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_events_type_enum" AS ENUM('sold', 'restocked', 'adjustment')`);
        await queryRunner.query(`CREATE TABLE "inventory_events" ("id" SERIAL NOT NULL, "product_id" integer NOT NULL, "product_variant_id" integer NOT NULL, "type" "public"."inventory_events_type_enum" NOT NULL, "quantity" numeric(10,2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2e23c05381d151be5dad80bbe10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" SERIAL NOT NULL, "store_id" integer NOT NULL, "name" character varying NOT NULL, "barcode" character varying(50), "slug" character varying(255), "description" text, "image_url" character varying(512), "images" json, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_f2ff0d6409027115aea231bc229" UNIQUE ("store_id", "barcode"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" SERIAL NOT NULL, "title" character varying(255) NOT NULL, "content" text, "media_url" character varying, "is_published" boolean NOT NULL DEFAULT false, "scheduled_at" TIMESTAMP, "facebook_post_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "facebookPagePageId" character varying, "productId" integer NOT NULL, CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "facebook_pages" ("page_id" character varying NOT NULL, "name" character varying NOT NULL, "category" character varying, "access_token" character varying, "last_updated" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "userId" integer, CONSTRAINT "UQ_ff57d4f5f300f2b7bf94f30df62" UNIQUE ("page_id", "userId"), CONSTRAINT "PK_d79dd6c6611a8b8aed0744d8520" PRIMARY KEY ("page_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."facebook_page_subscription_subscribed_fields_enum" AS ENUM('feed', 'messages')`);
        await queryRunner.query(`CREATE TABLE "facebook_page_subscription" ("id" SERIAL NOT NULL, "page_id" character varying NOT NULL, "subscribed_fields" "public"."facebook_page_subscription_subscribed_fields_enum" array NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "userId" integer, CONSTRAINT "PK_344879af3da4d4312df02db7d98" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" SERIAL NOT NULL, "content" character varying NOT NULL, "type" character varying NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "sender_id" character varying, "sender_name" character varying, "productName" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "userId" integer, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'blocked', 'pending')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "phone" character varying NOT NULL, "email" character varying, "password_hash" character varying, "status" "public"."users_status_enum" NOT NULL DEFAULT 'pending', "phone_verified_at" TIMESTAMP, "name" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a000cca60bcf04454e72769949" ON "users" ("phone") `);
        await queryRunner.query(`CREATE TABLE "customers" ("user_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_11d81cd7be87b6f8865b0cf7661" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE TABLE "user_sessions" ("id" SERIAL NOT NULL, "token" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "userId" integer, CONSTRAINT "UQ_dfd7d90cc40088a3a75d7dfd283" UNIQUE ("userId", "token"), CONSTRAINT "PK_e93e031a5fed190d4789b6bfd83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "admins" ("user_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2b901dd818a2a6486994d915a68" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_dashboard_enum" AS ENUM('basic', 'advanced')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_support_enum" AS ENUM('none', 'email', 'chat', 'VIP')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "description" text, "price" integer NOT NULL, "product_limit" integer, "post_limit" integer, "comment_message_limit" integer, "dashboard" "public"."subscriptions_dashboard_enum" NOT NULL DEFAULT 'basic', "notifications" boolean NOT NULL DEFAULT false, "smart_classification" boolean NOT NULL DEFAULT false, "support" "public"."subscriptions_support_enum" NOT NULL DEFAULT 'none', "additional_admins" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "store_visits" ("id" SERIAL NOT NULL, "store_id" integer NOT NULL, "session_id" uuid NOT NULL, "visitor_ip_hash" character varying(64), "user_agent" text, "referer" character varying(512), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b7ae8f7ee9d60e6070d49794878" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0884ca7fdd70519604620d6c5e" ON "store_visits" ("store_id", "session_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_52b9e2cef2b14a7a92b43d289d" ON "store_visits" ("store_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "store_themes" ("id" SERIAL NOT NULL, "store_id" integer NOT NULL, "config" jsonb NOT NULL DEFAULT '{}', "version" integer NOT NULL DEFAULT '1', "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_106d2c55078dfad89cd368b3949" UNIQUE ("store_id"), CONSTRAINT "REL_106d2c55078dfad89cd368b394" UNIQUE ("store_id"), CONSTRAINT "PK_4a04b5b770fcbbf0ccdf77886fa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "store_seo" ("id" SERIAL NOT NULL, "store_id" integer NOT NULL, "title" text, "description" text, "is_indexable" boolean NOT NULL DEFAULT true, "canonical_url" text, "og" jsonb, "twitter" jsonb, "schema_org" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_2112d143bc3c06c18428427a270" UNIQUE ("store_id"), CONSTRAINT "REL_2112d143bc3c06c18428427a27" UNIQUE ("store_id"), CONSTRAINT "PK_cc930f9003e68f49a3d1c15d0a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" SERIAL NOT NULL, "product_id" integer, "product_variant_id" integer, "name" character varying(255), "variant_label" character varying(100), "quantity" numeric(10,2) NOT NULL, "unit_price" numeric(10,2) NOT NULL, "total_price" numeric(10,2) NOT NULL, "orderId" integer NOT NULL, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."orders_order_source_enum" AS ENUM('whatsapp', 'web')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending', 'confirmed', 'shipped', 'cancelled', 'completed')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_payment_status_enum" AS ENUM('unpaid', 'paid')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" SERIAL NOT NULL, "store_id" integer NOT NULL, "customer_id" integer, "order_source" "public"."orders_order_source_enum" NOT NULL DEFAULT 'web', "buyer_name" character varying(255) NOT NULL, "buyer_phone" character varying(32) NOT NULL, "buyer_email" character varying(255), "shipping_address_line1" character varying(255) NOT NULL, "shipping_address_line2" character varying(255), "shipping_city" character varying(128) NOT NULL, "shipping_state" character varying(128), "shipping_postal_code" character varying(32), "notes" text, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'pending', "payment_status" "public"."orders_payment_status_enum" NOT NULL DEFAULT 'unpaid', "tracking_number" character varying(128), "internal_notes" text, "delivered_at" TIMESTAMP, "shipping_cost" numeric(10,2) NOT NULL DEFAULT '0', "total_amount" numeric(10,2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_links" ("id" SERIAL NOT NULL, "order_id" integer NOT NULL, "token" character varying(64) NOT NULL, "expires_at" TIMESTAMP NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_cb634e668602cba41f03b0809c7" UNIQUE ("token"), CONSTRAINT "REL_e04b2c56fdf5a98bb3c1f05274" UNIQUE ("order_id"), CONSTRAINT "PK_8604cd69ddc711b1aa03237884c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."custom_order_requests_status_enum" AS ENUM('pending', 'quoted', 'accepted', 'rejected', 'expired')`);
        await queryRunner.query(`CREATE TABLE "custom_order_requests" ("id" SERIAL NOT NULL, "store_id" integer NOT NULL, "customer_id" integer, "buyer_name" character varying(255) NOT NULL, "buyer_phone" character varying(32) NOT NULL, "description" text NOT NULL, "budget" numeric(10,2), "images" text, "status" "public"."custom_order_requests_status_enum" NOT NULL DEFAULT 'pending', "quoted_price" numeric(10,2), "quoted_shipping_cost" numeric(10,2), "seller_notes" text, "quoted_at" TIMESTAMP, "orderId" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_76d1c3f11fc931e327a6cc69823" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "push_subscriptions" ("id" SERIAL NOT NULL, "endpoint" text NOT NULL, "p256dh" text NOT NULL, "auth" text NOT NULL, "user_agent" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "userId" integer, CONSTRAINT "UQ_0008bdfd174e533a3f98bf9af16" UNIQUE ("endpoint"), CONSTRAINT "PK_757fc8f00c34f66832668dc2e53" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."merchants_onboarding_status_enum" AS ENUM('signup', 'business_type_selected', 'whatsapp_connected', 'store_created', 'products_added', 'live')`);
        await queryRunner.query(`CREATE TABLE "merchants" ("user_id" integer NOT NULL, "onboarding_status" "public"."merchants_onboarding_status_enum" NOT NULL DEFAULT 'signup', "primary_store_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_698f612a3134c503f711479a4e5" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."addons_addon_type_enum" AS ENUM('message_pack', 'staff_seat', 'product_pack', 'posts_pack')`);
        await queryRunner.query(`CREATE TABLE "addons" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "addon_type" "public"."addons_addon_type_enum" NOT NULL, "price" integer NOT NULL, "billing_cycle" character varying NOT NULL DEFAULT 'monthly', "provides_quantity" integer NOT NULL, "available_for_plans" json, "is_active" boolean NOT NULL DEFAULT true, "display_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_bf6897b3f7b2e6b712bdf01f297" UNIQUE ("name"), CONSTRAINT "UQ_359f971aa4b0ae502460f822caf" UNIQUE ("slug"), CONSTRAINT "PK_cd49fb3dc0558f02cb6fe6cc138" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_addons" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "addonId" integer NOT NULL, "quantity_purchased" integer NOT NULL DEFAULT '1', "status" character varying NOT NULL DEFAULT 'active', "expires_at" TIMESTAMP, "purchased_at" TIMESTAMP NOT NULL DEFAULT now(), "next_renewal_date" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_a04a0d7a13fe3bc0c02a88d80e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usage_tracking" ("id" SERIAL NOT NULL, "user_id" integer NOT NULL, "period_month" character varying(7) NOT NULL, "messages_received" integer NOT NULL DEFAULT '0', "posts_created" integer NOT NULL DEFAULT '0', "current_staff_count" integer NOT NULL DEFAULT '0', "last_reset_at" TIMESTAMP NOT NULL DEFAULT now(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2879a43395bb513204f88769aa6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" SERIAL NOT NULL, "key" character varying NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_017943867ed5ceef9c03edd9745" UNIQUE ("key"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."roles_scope_enum" AS ENUM('global', 'store')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "display_name" character varying, "scope" "public"."roles_scope_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" integer NOT NULL, "role_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE TABLE "store_user_roles" ("user_id" integer NOT NULL, "store_id" integer NOT NULL, "role_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5a1e5260c9485b7c8a75e2424ec" PRIMARY KEY ("user_id", "store_id", "role_id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" integer NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "PK_11d81cd7be87b6f8865b0cf7661"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "name" character varying(120)`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "whatsapp_number" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id")`);
        await queryRunner.query(`CREATE INDEX "IDX_11d81cd7be87b6f8865b0cf766" ON "customers" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7bfee32716cdb80a065fb83389" ON "customers" ("whatsapp_number") `);
        await queryRunner.query(`ALTER TABLE "user_identities" ADD CONSTRAINT "FK_084cef3785217102f222e90ea7c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" ADD CONSTRAINT "FK_2dfab576863bc3f84d4f6962274" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" ADD CONSTRAINT "FK_55c9f77733123bd2ead29886017" FOREIGN KEY ("planId") REFERENCES "plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stores" ADD CONSTRAINT "FK_ba95f3c2644552c72431cfb0c78" FOREIGN KEY ("owner_user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stores" ADD CONSTRAINT "FK_40abd374d12d7b19c471aa156cd" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_6343513e20e2deab45edfce1316" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_events" ADD CONSTRAINT "FK_f7ddfa78eb2478787f7cc5c3552" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_events" ADD CONSTRAINT "FK_fc45514a25429fcd5d8664f9b4e" FOREIGN KEY ("product_variant_id") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_68863607048a1abd43772b314ef" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_78eae136f1970a677a306e5871a" FOREIGN KEY ("facebookPagePageId") REFERENCES "facebook_pages"("page_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_59268dba986ee39a54affbdc00e" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facebook_pages" ADD CONSTRAINT "FK_f9811d917f02ed7ca5f86a617ff" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facebook_page_subscription" ADD CONSTRAINT "FK_703fdadd942ac83fd92ebb5392f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_11d81cd7be87b6f8865b0cf7661" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_sessions" ADD CONSTRAINT "FK_55fa4db8406ed66bc7044328427" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admins" ADD CONSTRAINT "FK_2b901dd818a2a6486994d915a68" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_visits" ADD CONSTRAINT "FK_886da8138ba4f90d84004f44d7c" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_themes" ADD CONSTRAINT "FK_106d2c55078dfad89cd368b3949" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_seo" ADD CONSTRAINT "FK_2112d143bc3c06c18428427a270" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_9263386c35b6b242540f9493b00" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_11836543386b9135a47d54cab70" FOREIGN KEY ("product_variant_id") REFERENCES "product_variants"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_b7a7bb813431fc7cd73cced0001" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_links" ADD CONSTRAINT "FK_e04b2c56fdf5a98bb3c1f052749" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" ADD CONSTRAINT "FK_896c63b51a136d131fc049326bc" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" ADD CONSTRAINT "FK_435af75bd28ed784b3c02bbed54" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" ADD CONSTRAINT "FK_5d28cd60ee855c630b01ae398d0" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" ADD CONSTRAINT "FK_4cc061875e9eecc311a94b3e431" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD CONSTRAINT "FK_698f612a3134c503f711479a4e5" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "merchants" ADD CONSTRAINT "FK_e04bed4eb6d5d47a851067e58a2" FOREIGN KEY ("primary_store_id") REFERENCES "stores"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_addons" ADD CONSTRAINT "FK_8753ec0cb42ad1c65652d6c68f4" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_addons" ADD CONSTRAINT "FK_08064120d6669a93246645afbbb" FOREIGN KEY ("addonId") REFERENCES "addons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usage_tracking" ADD CONSTRAINT "FK_97e15b4afbc1ebaad4f12080878" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_user_roles" ADD CONSTRAINT "FK_ac6fbd8586dd6fff743a9c93c1c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_user_roles" ADD CONSTRAINT "FK_aecccdfb2d7191d9505431b482d" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_user_roles" ADD CONSTRAINT "FK_a97091dcc6b28eab2b3813b55f0" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "store_user_roles" DROP CONSTRAINT "FK_a97091dcc6b28eab2b3813b55f0"`);
        await queryRunner.query(`ALTER TABLE "store_user_roles" DROP CONSTRAINT "FK_aecccdfb2d7191d9505431b482d"`);
        await queryRunner.query(`ALTER TABLE "store_user_roles" DROP CONSTRAINT "FK_ac6fbd8586dd6fff743a9c93c1c"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "usage_tracking" DROP CONSTRAINT "FK_97e15b4afbc1ebaad4f12080878"`);
        await queryRunner.query(`ALTER TABLE "user_addons" DROP CONSTRAINT "FK_08064120d6669a93246645afbbb"`);
        await queryRunner.query(`ALTER TABLE "user_addons" DROP CONSTRAINT "FK_8753ec0cb42ad1c65652d6c68f4"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP CONSTRAINT "FK_e04bed4eb6d5d47a851067e58a2"`);
        await queryRunner.query(`ALTER TABLE "merchants" DROP CONSTRAINT "FK_698f612a3134c503f711479a4e5"`);
        await queryRunner.query(`ALTER TABLE "push_subscriptions" DROP CONSTRAINT "FK_4cc061875e9eecc311a94b3e431"`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" DROP CONSTRAINT "FK_5d28cd60ee855c630b01ae398d0"`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" DROP CONSTRAINT "FK_435af75bd28ed784b3c02bbed54"`);
        await queryRunner.query(`ALTER TABLE "custom_order_requests" DROP CONSTRAINT "FK_896c63b51a136d131fc049326bc"`);
        await queryRunner.query(`ALTER TABLE "order_links" DROP CONSTRAINT "FK_e04b2c56fdf5a98bb3c1f052749"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_772d0ce0473ac2ccfa26060dbe9"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_b7a7bb813431fc7cd73cced0001"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_11836543386b9135a47d54cab70"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_9263386c35b6b242540f9493b00"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "store_seo" DROP CONSTRAINT "FK_2112d143bc3c06c18428427a270"`);
        await queryRunner.query(`ALTER TABLE "store_themes" DROP CONSTRAINT "FK_106d2c55078dfad89cd368b3949"`);
        await queryRunner.query(`ALTER TABLE "store_visits" DROP CONSTRAINT "FK_886da8138ba4f90d84004f44d7c"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP CONSTRAINT "FK_2b901dd818a2a6486994d915a68"`);
        await queryRunner.query(`ALTER TABLE "user_sessions" DROP CONSTRAINT "FK_55fa4db8406ed66bc7044328427"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_11d81cd7be87b6f8865b0cf7661"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "facebook_page_subscription" DROP CONSTRAINT "FK_703fdadd942ac83fd92ebb5392f"`);
        await queryRunner.query(`ALTER TABLE "facebook_pages" DROP CONSTRAINT "FK_f9811d917f02ed7ca5f86a617ff"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_59268dba986ee39a54affbdc00e"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_78eae136f1970a677a306e5871a"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_68863607048a1abd43772b314ef"`);
        await queryRunner.query(`ALTER TABLE "inventory_events" DROP CONSTRAINT "FK_fc45514a25429fcd5d8664f9b4e"`);
        await queryRunner.query(`ALTER TABLE "inventory_events" DROP CONSTRAINT "FK_f7ddfa78eb2478787f7cc5c3552"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_6343513e20e2deab45edfce1316"`);
        await queryRunner.query(`ALTER TABLE "stores" DROP CONSTRAINT "FK_40abd374d12d7b19c471aa156cd"`);
        await queryRunner.query(`ALTER TABLE "stores" DROP CONSTRAINT "FK_ba95f3c2644552c72431cfb0c78"`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" DROP CONSTRAINT "FK_55c9f77733123bd2ead29886017"`);
        await queryRunner.query(`ALTER TABLE "user_subscriptions" DROP CONSTRAINT "FK_2dfab576863bc3f84d4f6962274"`);
        await queryRunner.query(`ALTER TABLE "user_identities" DROP CONSTRAINT "FK_084cef3785217102f222e90ea7c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7bfee32716cdb80a065fb83389"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11d81cd7be87b6f8865b0cf766"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "PK_133ec679a801fab5e070f73d3ea"`);
        await queryRunner.query(`ALTER TABLE "customers" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "whatsapp_number"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "PK_11d81cd7be87b6f8865b0cf7661" PRIMARY KEY ("user_id")`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "store_user_roles"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_scope_enum"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "usage_tracking"`);
        await queryRunner.query(`DROP TABLE "user_addons"`);
        await queryRunner.query(`DROP TABLE "addons"`);
        await queryRunner.query(`DROP TYPE "public"."addons_addon_type_enum"`);
        await queryRunner.query(`DROP TABLE "merchants"`);
        await queryRunner.query(`DROP TYPE "public"."merchants_onboarding_status_enum"`);
        await queryRunner.query(`DROP TABLE "push_subscriptions"`);
        await queryRunner.query(`DROP TABLE "custom_order_requests"`);
        await queryRunner.query(`DROP TYPE "public"."custom_order_requests_status_enum"`);
        await queryRunner.query(`DROP TABLE "order_links"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_payment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_order_source_enum"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "store_seo"`);
        await queryRunner.query(`DROP TABLE "store_themes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52b9e2cef2b14a7a92b43d289d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0884ca7fdd70519604620d6c5e"`);
        await queryRunner.query(`DROP TABLE "store_visits"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_support_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_dashboard_enum"`);
        await queryRunner.query(`DROP TABLE "admins"`);
        await queryRunner.query(`DROP TABLE "user_sessions"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a000cca60bcf04454e72769949"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "facebook_page_subscription"`);
        await queryRunner.query(`DROP TYPE "public"."facebook_page_subscription_subscribed_fields_enum"`);
        await queryRunner.query(`DROP TABLE "facebook_pages"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "inventory_events"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_events_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31e615e1e93111f90aa7b5ed06"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP TYPE "public"."product_variants_unit_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f94c72515c300083297fac24fc"`);
        await queryRunner.query(`DROP TABLE "stores"`);
        await queryRunner.query(`DROP TYPE "public"."stores_type_enum"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "user_subscriptions"`);
        await queryRunner.query(`DROP TABLE "plans"`);
        await queryRunner.query(`DROP TABLE "user_identities"`);
        await queryRunner.query(`DROP TYPE "public"."user_identities_provider_enum"`);
    }

}
