name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.20.3'
      
      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Deploy to VPS via SSH
        if: success()
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: 22
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /path/to/your/app
            git pull origin main
            yarn install --production
            yarn run build
            pm2 restart core-api || pm2 start dist/main.js --name core-api